### ISSUE TITLE
csv-sorter giving the below error

### ISSUE THREAD

**Issue by Prasanna-Kumar-1** [wopperer/csv-sorter#2]
Hello @wopperer ,
When i used this plugin to sort a CSV file in my cypress test script, the below error is presented

I have installed this plugin as a Dev dependency and included below statement in my cypress scrip
const csv = require('csv-sorter');

![image](https://user-images.githubusercontent.com/57648011/161458932-c2fd0933-a707-439a-8676-a7615a52705e.png)

Please help

**Comment by wopperer** [comment]
Hi @Prasanna-Kumar-1,

this seems you are using the module from the client side (browser). Until now the module is intended to be used from a node.js environment only. In the future though im planning to add browser support too.

**Comment by wopperer** [comment]
browser support is now added with version 2.4.0
